# Generated by Django 5.2.12 on 2026-03-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(help_text="Le lien d'origine vers lequel rediriger", max_length=1000, verbose_name='URL cible')),
                ('short_code', models.CharField(help_text="Le mot clé pour le raccourci, ex: 'spotify'", max_length=50, unique=True, verbose_name='Code court')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Nombre de clics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Lien raccourci',
                'verbose_name_plural': 'Liens raccourcis',
                'ordering': ['-created_at'],
            },
        ),
    ]
