# Generated by Django 5.2.12 on 2026-03-11 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Nom de l'événement")),
                ('description', models.TextField(verbose_name="Description de l'événement")),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name="Image de l'événement")),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image (Ex: Unsplash)")),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'événement")),
                ('location', models.CharField(default='Yaoundé, Cameroun', max_length=200, verbose_name='Lieu')),
                ('role', models.CharField(max_length=100, verbose_name='Rôle (ex: Speaker & Lead Orga)')),
                ('role_icon', models.CharField(default='mic', max_length=50, verbose_name='Icône du rôle (ex: mic, users)')),
                ('official_site_url', models.URLField(blank=True, null=True, verbose_name='Lien site officiel')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Lien post LinkedIn')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien replay vidéo')),
                ('photos_url', models.URLField(blank=True, null=True, verbose_name='Lien galerie photos')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du tag')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('impact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Impact métier')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image de couverture')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image (Ex: Unsplash)")),
                ('icon', models.CharField(default='users', max_length=50, verbose_name='Icône Lucide (ex: users, bot)')),
                ('status', models.CharField(choices=[('production', 'En production'), ('poc', 'PoC / Démo'), ('development', 'En développement')], default='production', max_length=20, verbose_name='Statut')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='Lien de Démo')),
                ('article_url', models.URLField(blank=True, null=True, verbose_name="Lien de l'article (Medium)")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.tag')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'article")),
                ('summary', models.TextField(verbose_name='Extrait / Résumé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image de couverture')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image (Ex: Unsplash)")),
                ('medium_url', models.URLField(verbose_name='Lien Medium')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('read_time', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture (minutes)')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie principale (ex: Intelligence Artificielle)')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='portfolio.tag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la vidéo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Miniature')),
                ('thumbnail_url', models.URLField(blank=True, null=True, verbose_name='URL de la miniature (Ex: Unsplash)')),
                ('youtube_url', models.URLField(verbose_name='Lien YouTube')),
                ('duration', models.CharField(help_text='Ex: 14:25', max_length=10, verbose_name='Durée')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre à la une')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='portfolio.tag')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-published_date'],
            },
        ),
    ]
