# Generated by Django 5.2.12 on 2026-03-11 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la certification')),
                ('provider', models.CharField(max_length=100, verbose_name='Fournisseur (ex: Google, Coursera)')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'obtention")),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='Image de fond')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image (Ex: Unsplash)")),
                ('icon', models.CharField(default='award', max_length=50, verbose_name='Icône Lucide (ex: cloud, shield-check)')),
                ('verify_url', models.URLField(blank=True, null=True, verbose_name='Lien de vérification')),
                ('tags', models.ManyToManyField(blank=True, related_name='certifications', to='portfolio.tag')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
    ]
