# Generated by Django 5.2.12 on 2026-03-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise / Organisation')),
                ('period', models.CharField(max_length=100, verbose_name='Période (ex: Mai 2022 - Présent)')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('bullets', models.TextField(help_text='Un point par ligne', verbose_name='Tâches / Réalisations')),
                ('icon', models.CharField(default='briefcase', max_length=50, verbose_name='Icône Lucide')),
                ('color', models.CharField(default='blue-600', help_text='Couleur ex: blue-600, slate-400, purple-500', max_length=20, verbose_name="Couleur d'accent")),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre de la compétence')),
                ('icon', models.CharField(default='cloud', max_length=50, verbose_name='Icône Lucide')),
                ('color', models.CharField(default='blue', help_text='Couleur Tailwind (ex: blue, emerald, purple, red)', max_length=20, verbose_name='Couleur principale')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description optionnelle')),
                ('bullets', models.TextField(help_text='Un point par ligne', verbose_name='Points clés de la compétence')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Expertise (Skill)',
                'verbose_name_plural': 'Expertises (Skills)',
                'ordering': ['order'],
            },
        ),
    ]
