# Generated by Django 5.2.12 on 2026-03-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Catégorie principale (ex: Intelligence Artificielle)'),
        ),
        migrations.AddField(
            model_name='article',
            name='category_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Catégorie principale (ex: Intelligence Artificielle)'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_en',
            field=models.TextField(null=True, verbose_name='Extrait / Résumé'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_fr',
            field=models.TextField(null=True, verbose_name='Extrait / Résumé'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name="Titre de l'article"),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name="Titre de l'article"),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='certification',
            name='provider_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Fournisseur (ex: Google, Coursera)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='provider_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Fournisseur (ex: Google, Coursera)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre de la certification'),
        ),
        migrations.AddField(
            model_name='certification',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre de la certification'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True, verbose_name="Description de l'événement"),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fr',
            field=models.TextField(null=True, verbose_name="Description de l'événement"),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(default='Yaoundé, Cameroun', max_length=200, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_fr',
            field=models.CharField(default='Yaoundé, Cameroun', max_length=200, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='event',
            name='role_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Rôle (ex: Speaker & Lead Orga)'),
        ),
        migrations.AddField(
            model_name='event',
            name='role_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Rôle (ex: Speaker & Lead Orga)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name="Nom de l'événement"),
        ),
        migrations.AddField(
            model_name='event',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name="Nom de l'événement"),
        ),
        migrations.AddField(
            model_name='experience',
            name='bullets_en',
            field=models.TextField(help_text='Un point par ligne', null=True, verbose_name='Tâches / Réalisations'),
        ),
        migrations.AddField(
            model_name='experience',
            name='bullets_fr',
            field=models.TextField(help_text='Un point par ligne', null=True, verbose_name='Tâches / Réalisations'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Entreprise / Organisation'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Entreprise / Organisation'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre du poste'),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre du poste'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Impact métier'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Impact métier'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre du projet'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre du projet'),
        ),
        migrations.AddField(
            model_name='skill',
            name='bullets_en',
            field=models.TextField(help_text='Un point par ligne', null=True, verbose_name='Points clés de la compétence'),
        ),
        migrations.AddField(
            model_name='skill',
            name='bullets_fr',
            field=models.TextField(help_text='Un point par ligne', null=True, verbose_name='Points clés de la compétence'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description optionnelle'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description optionnelle'),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre de la compétence'),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre de la compétence'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nom du tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nom du tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre de la vidéo'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre de la vidéo'),
        ),
    ]
