# Generated by Django 5.2.12 on 2026-03-14 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_article_category_en_article_category_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/Heure')),
                ('page', models.CharField(max_length=300, verbose_name='Page visitée')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP (anonymisée)')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='Clé de session')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('country_code', models.CharField(blank=True, max_length=5, verbose_name='Code Pays')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navigateur')),
                ('browser_version', models.CharField(blank=True, max_length=30, verbose_name='Version navigateur')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name="Système d'exploitation")),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablette'), ('bot', 'Bot'), ('other', 'Autre')], default='other', max_length=20, verbose_name="Type d'appareil")),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Page de référence')),
                ('referrer_domain', models.CharField(blank=True, max_length=150, verbose_name='Domaine référent')),
                ('language', models.CharField(blank=True, max_length=20, verbose_name='Langue du navigateur')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent complet')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='portfolio_v_timesta_1027fe_idx'), models.Index(fields=['country_code'], name='portfolio_v_country_42955c_idx'), models.Index(fields=['device_type'], name='portfolio_v_device__f65237_idx'), models.Index(fields=['page'], name='portfolio_v_page_187943_idx')],
            },
        ),
    ]
