# Generated by Django 5.2.12 on 2026-03-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_add_visitor_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif (visible sur le site)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif (visible sur le site)'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif (visible sur le site)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif (visible sur le site)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif (visible sur le site)'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif (visible sur le site)'),
        ),
    ]
